version: '3'

services:
  vault:
    image: vault:1.3.0
    volumes:
      - vault_data:/vault
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  bitcoind:
    image: quay.io/openware/bitcoind:0.17.1
    restart: always
    volumes:
      - ../data/bitcoin:/bitcoin
      - ../config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

volumes:
  vault_data:
